export const SET_LANGUAGE = "SET_LANGUAGE";
export const ADD_ARTICLES = "ADD_ARTICLES";
export const CLEAR_ARTICLES = "CLEAR_ARTICLES";
export const SET_SEARCH_KEY = "SET_SEARCH_KEY";
export const SET_IMAGES = "SET_IMAGES";
export const SET_ARTICLE_TAGS = "SET_ARTICLE_TAGS";
export const SET_CATEGORY_TAGS = "SET_CATEGORY_TAGS";
export const SET_VIDEOS = "SET_VIDEOS";
